### ISSUE TITLE
session.get("user_id")  does not work on @me endpoint 

### ISSUE THREAD

**Issue by linda-benboudiaf** [ahnaf-zamil/flask-react-session-authenticaton-tutorial#1]
It seems like the cookie session is created and the user_id is taken in account on login endpoint `session["user_id"] = userid` but when the call on /@me the `userid = session.get("user_id")` always return None. 

It seems like it does not save the `user_id` in the session

I use : NextJs app and Postgresql

**Comment by ahnaf-zamil** [comment]
Hello, thanks for making the issue.

Back when I used Next.js, I tried to do the same thing with sessions and it just didn't work. I couldn't figure out why for a while but my hypothesis is that the Flask session invoked by Next is on it's server side, and not client side.

For this reason, the session is not persisted on the client but is managed by the Next server or something (which is not accessible on client sided requests), at least that's what I think it is. Can't tell frankly, I don't use Next a lot so I may be wrong.

And it was for a few reasons along with this one why I switched to React only. Unfortunately I don't have enough knowledge or capability in Next.js to help you with this. But it does work with React 100%, I've used this method on a lot of my projects.

**Comment by linda-benboudiaf** [comment]
Indeed the problem is very common apparently Next.js is a client-side rendering framework, and it doesn't handle server-side session management out of the box like Flask does.

In this case it is better to use another solution like : JWT (JSON Web Tokens). 

Hope it can help someone 🥇
